# Generated by Django 2.2.17 on 2020-12-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='name',
            new_name='product_name',
        ),
        migrations.AddField(
            model_name='products',
            name='product_des',
            field=models.CharField(default='product description', max_length=300),
        ),
        migrations.AddField(
            model_name='products',
            name='product_img',
            field=models.ImageField(default='/home/kni9ht/Documents/DBMS_WDL/computerParts/computerParts/static/assets/img/error.png', height_field=273, upload_to=None, width_field=218),
        ),
    ]
