# Generated by Django 2.2.17 on 2020-12-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20201204_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_img',
        ),
        migrations.AddField(
            model_name='product',
            name='product_date',
            field=models.DateField(auto_now=True),
        ),
    ]
