# Generated by Django 2.2.17 on 2020-12-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_product_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_value',
            field=models.IntegerField(default=1),
        ),
    ]
